"""move to 3rd form

Revision ID: 565e0590aa2b
Revises: 
Create Date: 2023-12-29 14:15:35.974600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '565e0590aa2b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eo',
                    sa.Column('eo_id', sa.BIGINT(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=1024), nullable=True),
                    sa.Column('type_name', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('parent', sa.VARCHAR(length=1024), nullable=True),
                    sa.Column('region_name', sa.VARCHAR(length=1024), nullable=True),
                    sa.Column('area_name', sa.VARCHAR(length=1024), nullable=True),
                    sa.Column('ter_name', sa.VARCHAR(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('eo_id')
                    )
    op.create_table('pt',
                    sa.Column('pt_id', sa.BIGINT(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=1024), nullable=True),
                    sa.Column('region_name', sa.VARCHAR(length=1024), nullable=True),
                    sa.Column('area_name', sa.VARCHAR(length=1024), nullable=True),
                    sa.Column('ter_name', sa.VARCHAR(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('pt_id')
                    )
    op.create_table('registration',
                    sa.Column('reg_id', sa.BIGINT(), autoincrement=True, nullable=False),
                    sa.Column('reg_name', sa.VARCHAR(length=1024), nullable=True),
                    sa.Column('reg_type_name', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('area_name', sa.VARCHAR(length=1024), nullable=True),
                    sa.Column('ter_name', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('ter_type_name', sa.VARCHAR(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('reg_id')
                    )
    op.create_table('ukr_test',
                    sa.Column('test_id', sa.BIGINT(), autoincrement=True, nullable=False),
                    sa.Column('status', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('language', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('ball100', sa.FLOAT(), nullable=True),
                    sa.Column('ball12', sa.BIGINT(), nullable=True),
                    sa.Column('ball', sa.BIGINT(), nullable=True),
                    sa.Column('adapt_scale', sa.BIGINT(), nullable=False),
                    sa.Column('pt_id', sa.BIGINT(), nullable=False),
                    sa.ForeignKeyConstraint(['pt_id'], ['pt.pt_id'], ),
                    sa.PrimaryKeyConstraint('test_id')
                    )
    op.create_table('applicant',
                    sa.Column('out_id', sa.VARCHAR(length=36), nullable=False),
                    sa.Column('birth', sa.BIGINT(), nullable=True),
                    sa.Column('sex_type_name', sa.VARCHAR(length=50), nullable=True),
                    sa.Column('reg_id', sa.BIGINT(), nullable=False),
                    sa.Column('class_profile_name', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('class_lang_name', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('eo_id', sa.BIGINT(), nullable=False),
                    sa.Column('ukr_test_id', sa.BIGINT(), nullable=False),
                    sa.ForeignKeyConstraint(['eo_id'], ['eo.eo_id'], ),
                    sa.ForeignKeyConstraint(['reg_id'], ['registration.reg_id'], ),
                    sa.ForeignKeyConstraint(['ukr_test_id'], ['ukr_test.test_id'], ),
                    sa.PrimaryKeyConstraint('out_id')
                    )
    # op.drop_table('zno2020')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zno2020',
                    sa.Column('outid', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('birth', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('sextypename', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('regname', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('areaname', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('tername', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('regtypename', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('tertypename', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('classprofilename', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('classlangname', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('eoname', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('eotypename', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('eoregname', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('eoareaname', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('eotername', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('eoparent', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('ukrtest', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('ukrteststatus', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('ukrball100', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('ukrball12', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('ukrball', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('ukradaptscale', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('ukrptname', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('ukrptregname', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('ukrptareaname', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('ukrpttername', sa.TEXT(), autoincrement=False, nullable=True)
                    )
    op.drop_table('applicant')
    op.drop_table('ukr_test')
    op.drop_table('registration')
    op.drop_table('pt')
    op.drop_table('eo')
    # ### end Alembic commands ###
